service: babymonitor

provider:
  name: aws
  runtime: nodejs16.x
  logs:
    httpApi: true
  httpApi:
    cors: true

functions:
  index:
    handler: dist/index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline
