service: babymonitor

provider:
  name: aws
  runtime: nodejs16.x
  logs:
    httpApi: true
  httpApi:
    cors: true

functions:
  app:
    handler: dist/app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-offline
